const express=require('express'),bcrypt=require('bcryptjs'),assert=require('assert');
const {mountAdmin,DENY_MSG}=require('./admin-auth');
let lastOtp; const app=express();
mountAdmin(app,{sendMail:async(to,s,t)=>{lastOtp=t.match(/\d{16}/)[0];lastOtp_to=to;},
 env:{OWNER_EMAIL:'Owner@Gmail.com',OWNER_PASSWORD_HASH:bcrypt.hashSync('Str0ng!Pass',10),ADMIN_JWT_SECRET:'x'.repeat(48)}});
app.get('/admin/dashboard',(q,r)=>r.send('DASH'));
app.get('/api/admin/users',(q,r)=>r.json({ok:1}));
const jwt=require('jsonwebtoken');
(async()=>{const s=app.listen(0);const B='http://localhost:'+s.address().port;
 const post=(p,b,h={})=>fetch(B+p,{method:'POST',headers:{'content-type':'application/json',...h},body:JSON.stringify(b)});
 const T=async(n,f)=>{await f();console.log('PASS',n)};
 await T('no session -> 401 API',async()=>assert.equal((await fetch(B+'/api/admin/users')).status,401));
 await T('page w/o session redirects to login',async()=>{const r=await fetch(B+'/admin/dashboard',{redirect:'manual'});assert.equal(r.headers.get('location'),'/admin-login.html')});
 await T('wrong email+right pw rejected',async()=>assert.equal((await post('/api/admin/auth/login',{email:'x@gmail.com',password:'Str0ng!Pass'})).status,401));
 await T('owner email wrong pw rejected',async()=>assert.equal((await post('/api/admin/auth/login',{email:'owner@gmail.com',password:'bad'})).status,401));
 await T('role in body ignored',async()=>assert.equal((await post('/api/admin/auth/login',{email:'x@gmail.com',password:'Str0ng!Pass',role:'admin'})).status,401));
 let r=await post('/api/admin/auth/login',{email:'OWNER@gmail.com',password:'Str0ng!Pass'});const {challengeId}=await r.json();
 await T('login ok, OTP 16 digits',()=>assert.equal(lastOtp.length,16));
 await T('wrong OTP rejected',async()=>assert.equal((await post('/api/admin/auth/verify-otp',{challengeId,otp:'1'.repeat(16)})).status,401));
 r=await post('/api/admin/auth/verify-otp',{challengeId,otp:lastOtp});
 const ck=r.headers.get('set-cookie').split(';')[0];
 await T('correct OTP -> session',()=>assert.equal(r.status,200));
 await T('OTP single-use',async()=>assert.equal((await post('/api/admin/auth/verify-otp',{challengeId,otp:lastOtp})).status,401));
 await T('owner reaches admin API',async()=>assert.equal((await fetch(B+'/api/admin/users',{headers:{cookie:ck}})).status,200));
 await T('owner reaches admin page',async()=>assert.equal(await (await fetch(B+'/admin/dashboard',{headers:{cookie:ck}})).text(),'DASH'));
 const forged=jwt.sign({sub:'attacker@gmail.com',sid:'fake',role:'admin'},'x'.repeat(48));
 await T('forged JWT (right secret, fake sid) rejected',async()=>assert.equal((await fetch(B+'/api/admin/users',{headers:{cookie:'gcp_admin='+forged}})).status,401));
 await T('alg none/other secret rejected',async()=>assert.equal((await fetch(B+'/api/admin/users',{headers:{cookie:'gcp_admin='+jwt.sign({sub:'owner@gmail.com'},'wrong')}})).status,401));
 r=await fetch(B+'/api/admin/users',{headers:{cookie:'gcp_token=normaluser'}});
 await T('normal/SSO user -> 403 + exact message',async()=>{assert.equal(r.status,403);assert.equal((await r.json()).error,DENY_MSG)});
 r=await fetch(B+'/admin/dashboard',{headers:{cookie:'gcp_token=normaluser'},redirect:'manual'});
 await T('normal user page -> redirected away',()=>assert.equal(r.headers.get('location'),'/?denied=owner'));
 await post('/api/admin/auth/logout',{},{cookie:ck});
 await T('after logout session dead',async()=>assert.equal((await fetch(B+'/api/admin/users',{headers:{cookie:ck}})).status,401));
 s.close();})().catch(e=>{console.error('FAIL',e.message);process.exit(1)});
