import { QuickDigitalService, QuickFixOrder } from '../src/types';

export const quickServicesInitialData: QuickDigitalService[] = [
  // 1. Background Removal
  {
    id: 'qs-bg-removal',
    name: 'Background Removal',
    category: 'Image Fix',
    description: 'Remove the background from your image cleanly and professionally with smooth edge preservation.',
    price: 49,
    deliveryTime: 'Same Day (1-2 hrs)',
    iconName: 'Eraser',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Extract subject on transparent background',
      'Remove busy or messy studio background',
      'Extract model with fine hair / fur details',
      'Isolate product with sharp clean edges',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP', 'HEIC'],
    exampleBeforeImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    exampleAfterImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
  },
  // 2. Background Change
  {
    id: 'qs-bg-change',
    name: 'Background Change',
    category: 'Image Fix',
    description: 'Replace dull or unsuitable backgrounds with pure white, studio marble, gradient, or aesthetic scenery.',
    price: 79,
    deliveryTime: 'Same Day',
    iconName: 'Image',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Replace with pure white background (#FFFFFF)',
      'Add luxury marble / aesthetic studio backdrop',
      'Add natural outdoor/lifestyle background',
      'Apply subtle soft studio drop gradient',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
    exampleBeforeImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80',
    exampleAfterImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80',
  },
  // 3. Object/Person Removal
  {
    id: 'qs-object-removal',
    name: 'Object / Person Removal',
    category: 'Image Fix',
    description: 'Erase photobombers, unwanted people, trash, wires, or distracting elements without leaving traces.',
    price: 99,
    deliveryTime: 'Same Day',
    iconName: 'UserX',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Erase photobombers / strangers in photo',
      'Remove background clutter, trash, or vehicles',
      'Remove wires, power poles, or glare',
      'Remove price tags or security tags from product',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP', 'RAW'],
    exampleBeforeImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    exampleAfterImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
  },
  // 4. Image Cropping
  {
    id: 'qs-image-cropping',
    name: 'Image Cropping & Re-Framing',
    category: 'Image Fix',
    description: 'Crop and reframe your subject with perfect rule-of-thirds composition and exact pixel dimensions.',
    price: 39,
    deliveryTime: '1-2 Hours',
    iconName: 'Crop',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Center subject and balance framing',
      'Crop out unwanted edges or borders',
      'Reframe landscape image into portrait',
      'Crop tight product detail shot',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 5. Image Resize
  {
    id: 'qs-image-resize',
    name: 'Image Resize & Scaling',
    category: 'Image Fix',
    description: 'Resize image to exact width and height specifications without distortion or pixel stretching.',
    price: 39,
    deliveryTime: '1-2 Hours',
    iconName: 'Maximize2',
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Resize to exact pixel dimensions (e.g. 1920x1080, 2000x2000)',
      'Upscale or downscale while maintaining crisp aspect ratio',
      'Standardize batch image dimensions',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 6. Image Ratio Change
  {
    id: 'qs-ratio-change',
    name: 'Image Ratio Change (1:1, 4:5, 9:16)',
    category: 'Image Fix',
    description: 'Convert between 1:1 square, 16:9 widescreen, 4:5 portrait, and 9:16 vertical with intelligent canvas expansion.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'Columns',
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Convert 16:9 to 1:1 Square without cutting subject',
      'Extend canvas sides naturally for 9:16 Story format',
      'Change 4:3 to 4:5 Instagram feed ratio',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 7. Image Compression
  {
    id: 'qs-image-compression',
    name: 'Image Compression & Web Optimization',
    category: 'Image Fix',
    description: 'Reduce file size under 1MB / 500KB / 100KB for website speed or portal uploads with zero visible quality loss.',
    price: 39,
    deliveryTime: '1-2 Hours',
    iconName: 'Minimize2',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Compress under 500KB for portal / job application upload',
      'Compress website banners under 150KB for fast SEO loading',
      'Batch compress product images under 2MB',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF', 'WEBP'],
  },
  // 8. Image Quality Enhancement
  {
    id: 'qs-quality-enhancement',
    name: 'Image Quality Enhancement',
    category: 'Image Fix',
    description: 'Boost clarity, micro-contrast, color depth, exposure, and dynamic range for striking visuals.',
    price: 99,
    deliveryTime: 'Same Day',
    iconName: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Fix dull, washed-out colors and bad lighting',
      'Enhance product texture, leather, fabric, or metallic shine',
      'Balance dark shadows and blown-out highlights',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP', 'RAW'],
  },
  // 9. Blurry Image Fix
  {
    id: 'qs-blurry-fix',
    name: 'Blurry Image Fix & De-Noise',
    category: 'Image Fix',
    description: 'Sharpen out-of-focus photos, reconstruct soft edges, and recover lost details using advanced de-blur techniques.',
    price: 99,
    deliveryTime: 'Same Day',
    iconName: 'Eye',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Sharpen motion blur from shaky camera',
      'Fix soft-focus portrait face details',
      'Enhance blurred receipt / text / document capture',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 10. Transparent PNG Creation
  {
    id: 'qs-transparent-png',
    name: 'Transparent PNG Creation',
    category: 'Image Fix',
    description: 'Convert opaque white/black JPG logos and graphics into clean, transparent 32-bit PNGs ready for overlays.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'Layers',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Make white/black background 100% transparent',
      'Deliver high-res PNG file with crisp alpha channel',
      'Remove background inside letter cutouts (O, P, A, D, etc.)',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP', 'PDF'],
  },
  // 11. Color Change
  {
    id: 'qs-color-change',
    name: 'Color Change (Recoloring)',
    category: 'Image Fix',
    description: 'Change the color of clothing, vehicles, furniture, products, hair, or graphics accurately to any hex shade.',
    price: 79,
    deliveryTime: 'Same Day',
    iconName: 'Palette',
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Change apparel / dress / t-shirt color to specific shade',
      'Generate multiple product color variants without reshooting',
      'Recolor vehicle / wall / furniture upholstery',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PSD'],
  },
  // 12. Product Photo Cleanup
  {
    id: 'qs-product-cleanup',
    name: 'Product Photo Cleanup',
    category: 'E-commerce Fix',
    description: 'Clean scratches, dust particles, fingerprints, sensor spots, and manufacturing defects from product shots.',
    price: 89,
    deliveryTime: 'Same Day',
    iconName: 'Sparkle',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Remove dust, lint, and hair fibers from merchandise',
      'Eliminate surface scratches and scuff marks',
      'Fix packaging wrinkles and label bubbles',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'RAW'],
  },
  // 13. Product Shadow Creation
  {
    id: 'qs-product-shadow',
    name: 'Product Shadow & Reflection',
    category: 'E-commerce Fix',
    description: 'Add natural realistic drop shadows, cast ground shadows, or luxury reflection shadows to floating products.',
    price: 79,
    deliveryTime: 'Same Day',
    iconName: 'Sun',
    imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Add natural soft contact shadow on white background',
      'Add glossy reflective mirror floor shadow',
      'Create 3D floating cast drop shadow',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PSD'],
  },
  // 14. Logo Cleanup
  {
    id: 'qs-logo-cleanup',
    name: 'Logo Cleanup & Vectorization',
    category: 'Logo Fix',
    description: 'Redraw pixelated, fuzzy, or low-res logos into razor-sharp scalable vector graphics (SVG/PNG/PDF/AI).',
    price: 149,
    deliveryTime: 'Same Day',
    iconName: 'PenTool',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Recreate low-res blurry logo in crisp vector format',
      'Fix jagged edges, artifacts, and pixelation',
      'Deliver high-res printable transparent files',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF', 'Screenshot'],
  },
  // 15. Logo Background Removal
  {
    id: 'qs-logo-bg-removal',
    name: 'Logo Background Removal',
    category: 'Logo Fix',
    description: 'Strip solid white, black, or colored background from your logo file with pristine edge anti-aliasing.',
    price: 59,
    deliveryTime: '1-2 Hours',
    iconName: 'Shield',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Remove solid box background from logo for website header',
      'Extract intricate logo shapes cleanly',
      'Provide transparent PNG and SVG formats',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF'],
  },
  // 16. Logo Quality Improvement
  {
    id: 'qs-logo-quality',
    name: 'Logo Quality & 4K Upscale',
    category: 'Logo Fix',
    description: 'Upscale tiny 200px logo screenshots into 4000px ultra-high-definition graphics suitable for billboard prints.',
    price: 149,
    deliveryTime: 'Same Day',
    iconName: 'Award',
    imageUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Upscale 10x with zero pixelation or degradation',
      'Sharpen custom type and brand emblem contours',
      'Align typography and geometric symmetry',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF'],
  },
  // 17. Image Text Removal
  {
    id: 'qs-text-removal',
    name: 'Image Text & Watermark Removal',
    category: 'Image Fix',
    description: 'Seamlessly remove watermarks, date stamps, copyright text, subtitles, or old typography from photos.',
    price: 69,
    deliveryTime: '1-2 Hours',
    iconName: 'Type',
    imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Remove camera timestamps, date stamps, or GPS overlays',
      'Clean unwanted promo text or old discount stickers',
      'Reconstruct texture behind deleted text',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 18. Image Text Addition
  {
    id: 'qs-text-addition',
    name: 'Image Text Addition & Typography',
    category: 'Image Fix',
    description: 'Add typography, titles, pricing badges, watermarks, or call-to-actions with professional designer layout.',
    price: 69,
    deliveryTime: '1-2 Hours',
    iconName: 'Edit3',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Add brand watermark or copyright line',
      'Overlay modern promo badge ("50% OFF", "Best Seller")',
      'Add caption or contact phone number elegantly',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PSD'],
  },
  // 19. Font Identification
  {
    id: 'qs-font-identification',
    name: 'Font Identification & Specimen',
    category: 'Logo Fix',
    description: 'Identify exact font names, foundry licenses, and free/commercial alternatives from any image screenshot.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'Search',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Identify font used in screenshot or competitor graphic',
      'Find identical free Google Font alternatives',
      'Provide direct font download / purchase links',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'Screenshot'],
  },
  // 20. Brand Color Identification
  {
    id: 'qs-color-identification',
    name: 'Brand Color Palette & Swatches',
    category: 'Logo Fix',
    description: 'Extract exact HEX, RGB, CMYK, and Pantone swatch codes from your logo or brand asset with color harmony specs.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'Droplets',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Extract primary and secondary HEX / RGB codes',
      'Convert digital screen colors to accurate CMYK Pantone for print',
      'Generate a 1-page mini Brand Color Palette PDF',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF'],
  },
  // 21. Social Media Size Conversion
  {
    id: 'qs-social-media-pack',
    name: 'Social Media Size Master Pack',
    category: 'Social Media Fix',
    description: 'Adapt a single creative into all platform sizes (IG Post 1:1, Story 9:16, FB Cover 16:9, LinkedIn Banner).',
    price: 59,
    deliveryTime: '1-2 Hours',
    iconName: 'Share2',
    imageUrl: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Convert 1 creative into multi-platform formats',
      'Ensure focal points and text stay within safe viewing zones',
      'Deliver labeled PNGs for each social network',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PSD'],
  },
  // 22. Instagram Post Resize
  {
    id: 'qs-ig-post-resize',
    name: 'Instagram Post Resize (1:1 / 4:5)',
    category: 'Social Media Fix',
    description: 'Format photos perfectly for Instagram feed at 1080x1080 (Square) or 1080x1350 (Portrait) without awkward cropping.',
    price: 39,
    deliveryTime: '1-2 Hours',
    iconName: 'Instagram',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Convert wide banner to 1080x1080 without squishing',
      'Optimize to 1080x1350 4:5 maximum feed real estate',
      'Add blur background or white border padding',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 23. Instagram Story Resize
  {
    id: 'qs-ig-story-resize',
    name: 'Instagram Story & Reel (9:16)',
    category: 'Social Media Fix',
    description: 'Format photos and graphics for 1080x1920 Full HD vertical Stories with safe-zone margin checks.',
    price: 39,
    deliveryTime: '1-2 Hours',
    iconName: 'Smartphone',
    imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Convert horizontal photo to full-screen 9:16 Story',
      'Prevent username header and bottom reply box clipping',
      'Add stylish blurred background canvas expansion',
    ],
    supportedFileTypes: ['JPG', 'PNG'],
  },
  // 24. YouTube Thumbnail Resize
  {
    id: 'qs-yt-thumbnail-resize',
    name: 'YouTube Thumbnail (1280x720 HD)',
    category: 'Social Media Fix',
    description: 'Optimize video thumbnails to 1280x720 HD under 2MB with high-contrast text and crisp mobile pop.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'Video',
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Resize to exact 1280x720 16:9 YouTube specification',
      'Compress under YouTube 2MB upload limit',
      'Sharpen thumbnail for mobile browse views',
    ],
    supportedFileTypes: ['JPG', 'PNG'],
  },
  // 25. WhatsApp DP Resize
  {
    id: 'qs-whatsapp-dp-resize',
    name: 'WhatsApp DP & Profile Picture',
    category: 'Social Media Fix',
    description: 'Fit your complete portrait or company logo inside WhatsApp circular profile picture without cropping corners.',
    price: 39,
    deliveryTime: '1-2 Hours',
    iconName: 'MessageCircle',
    imageUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Fit full photo without cropping head or shoulders',
      'Circular preview safe-zone verification',
      'High-resolution square 1000x1000 export',
    ],
    supportedFileTypes: ['JPG', 'PNG'],
  },
  // 26. Print-Ready File Fix
  {
    id: 'qs-print-ready-fix',
    name: 'Print-Ready Fix (CMYK & 300 DPI)',
    category: 'Print Fix',
    description: 'Convert RGB web files to CMYK 300 DPI with 3mm bleed margins, crop marks, and embedded fonts for offset printing.',
    price: 149,
    deliveryTime: 'Same Day',
    iconName: 'Printer',
    imageUrl: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Convert 72 DPI screen file to 300 DPI high-res print file',
      'Convert RGB color mode to CMYK without muddy colors',
      'Add 3mm bleed margins and printer crop cut marks',
    ],
    supportedFileTypes: ['PDF', 'JPG', 'PNG', 'PSD', 'AI'],
  },
  // 27. PDF to Image
  {
    id: 'qs-pdf-to-image',
    name: 'PDF to High-Res Image (JPG/PNG)',
    category: 'File Conversion',
    description: 'Extract pages or graphics from vector PDFs into 300 DPI ultra-sharp JPG or transparent PNG images.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'FileText',
    imageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Extract single or all pages as crystal-clear 300 DPI images',
      'Extract vector graphics on transparent background',
      'Convert protected or read-only PDF sheets to JPG',
    ],
    supportedFileTypes: ['PDF'],
  },
  // 28. Image to PDF
  {
    id: 'qs-image-to-pdf',
    name: 'Image to Print-Quality PDF',
    category: 'File Conversion',
    description: 'Combine single or multiple images into a clean, searchable, vectorized A4/Letter multi-page PDF.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'File',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Merge multiple photo scans into 1 organized PDF',
      'Standardize page sizes to A4 / US Letter',
      'Optimize file size for email attachment',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 29. JPG to PNG
  {
    id: 'qs-jpg-to-png',
    name: 'JPG to Transparent PNG',
    category: 'File Conversion',
    description: 'Convert compressed JPGs into lossless PNG-24 files with background extraction and color enhancement.',
    price: 39,
    deliveryTime: '1-2 Hours',
    iconName: 'Repeat',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Convert lossy JPG to uncompressed transparent PNG',
      'Eliminate JPG block compression noise',
    ],
    supportedFileTypes: ['JPG', 'JPEG'],
  },
  // 30. PNG to JPG
  {
    id: 'qs-png-to-jpg',
    name: 'PNG to Optimized JPG',
    category: 'File Conversion',
    description: 'Convert heavy PNGs into lightweight 100% quality JPGs with customizable matte background color.',
    price: 39,
    deliveryTime: '1-2 Hours',
    iconName: 'RefreshCw',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Convert heavy 15MB PNG to 500KB high-quality JPG',
      'Set background to pure white or solid color',
    ],
    supportedFileTypes: ['PNG'],
  },
  // 31. Document Scan Cleanup
  {
    id: 'qs-doc-scan-cleanup',
    name: 'Document & Receipt Scan Cleanup',
    category: 'Print Fix',
    description: 'Clean shadowed smartphone photos of receipts, certificates, bills, or notes into flat, bright document scans.',
    price: 79,
    deliveryTime: 'Same Day',
    iconName: 'FileCheck',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Remove dark finger shadows and desk background',
      'Perspective de-skew and straighten crooked pages',
      'Enhance black ink contrast on white paper',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF'],
  },
  // 32. Signature Cleanup
  {
    id: 'qs-signature-cleanup',
    name: 'Signature Cleanup & Vectorization',
    category: 'Print Fix',
    description: 'Turn a phone photo of your pen signature into a clean, transparent digital signature file for invoices & contracts.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'Feather',
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Extract ink signature on transparent background',
      'Clean paper texture, yellowing, and shadows',
      'Deliver in Blue and Black ink versions',
    ],
    supportedFileTypes: ['JPG', 'PNG'],
  },
  // 33. Passport/ID Photo Formatting
  {
    id: 'qs-passport-photo-format',
    name: 'Passport & Visa ID Photo Format',
    category: 'Print Fix',
    description: 'Format selfie or camera photo into official 2x2 inch / 35x45mm passport spec with white/blue background.',
    price: 69,
    deliveryTime: '1-2 Hours',
    iconName: 'UserCheck',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Change background to official plain white or light blue',
      'Crop to exact biometric passport dimensions (e.g. 2x2 in / 35x45mm)',
      'Create 8-photo printable 4x6 sheet layout',
    ],
    supportedFileTypes: ['JPG', 'PNG'],
  },
  // 34. Old Design Modernization
  {
    id: 'qs-design-modernization',
    name: 'Old Design Modernization',
    category: 'Photo Fix',
    description: 'Refresh outdated flyers, brochures, menu cards, or badges with modern typography and sleek aesthetics.',
    price: 199,
    deliveryTime: 'Same Day',
    iconName: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1509343256512-d77a5cb3791b?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Upgrade outdated layout to modern minimalist look',
      'Replace old fonts with contemporary typography',
      'Improve readability and visual hierarchy',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF', 'PSD'],
  },
  // 35. Design Alignment Fix
  {
    id: 'qs-alignment-fix',
    name: 'Design Alignment & Spacing Fix',
    category: 'Photo Fix',
    description: 'Fix uneven margins, crooked columns, unaligned icons, and awkward element spacing in existing designs.',
    price: 79,
    deliveryTime: '1-2 Hours',
    iconName: 'AlignLeft',
    imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Fix messy margins and unequal grid padding',
      'Align logos, headers, and bullet points perfectly',
      'Balance optical white space',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF', 'PSD'],
  },
  // 36. Spelling/Text Correction
  {
    id: 'qs-spelling-correction',
    name: 'Spelling & Text Correction in Image',
    category: 'Photo Fix',
    description: 'Correct typos, change phone numbers, update dates, or fix prices inside flattened image files seamlessly.',
    price: 49,
    deliveryTime: '1-2 Hours',
    iconName: 'CheckSquare',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Fix typo / spelling error with matching font and texture',
      'Update phone number, address, or website URL in banner',
      'Change year or price tag in flattened graphic',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'PDF'],
  },
  // 37. Low Resolution Image Fix
  {
    id: 'qs-lowres-fix',
    name: 'Low Resolution 4K Image Recovery',
    category: 'Image Fix',
    description: 'Reconstruct pixelated web images with neural super-resolution to recover crisp edge details.',
    price: 99,
    deliveryTime: 'Same Day',
    iconName: 'ZoomIn',
    imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Upscale 4x without jagged edges or noise',
      'Recover fine facial or product details from small thumbnail',
      'Clean JPEG compression artifact boxes',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 38. Marketplace Image Size Fix
  {
    id: 'qs-marketplace-size-fix',
    name: 'E-Commerce Marketplace Proportion Fix',
    category: 'E-commerce Fix',
    description: 'Standardize catalog photos for Shopify, Etsy, Meesho, or custom e-commerce stores with uniform proportions.',
    price: 59,
    deliveryTime: '1-2 Hours',
    iconName: 'ShoppingBag',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    enabled: true,
    commonProblems: [
      'Format to uniform 1:1 2000x2000px or 3:4 aspect ratio',
      'Center products with consistent 15% margin padding',
      'Ensure web-optimized fast-loading file sizes',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'WEBP'],
  },
  // 39. Amazon Main Image Fix
  {
    id: 'qs-amazon-image-fix',
    name: 'Amazon Main Image (Pure White RGB 255)',
    category: 'E-commerce Fix',
    description: 'Format product hero shots to 100% comply with strict Amazon guidelines: Pure White (255,255,255) & 85% frame fill.',
    price: 79,
    deliveryTime: 'Same Day',
    iconName: 'CheckCircle',
    imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=800&q=80',
    popular: true,
    recommended: true,
    enabled: true,
    commonProblems: [
      'Guarantee 100% Pure White RGB (255, 255, 255) background',
      'Scale product to occupy 85%+ of image frame',
      'Remove unapproved props, watermarks, and badges',
      'Deliver 2000x2000px high-res file for Amazon zoom feature',
    ],
    supportedFileTypes: ['JPG', 'PNG', 'TIFF'],
  },
  // 40. Flipkart Product Image Fix
  {
    id: 'qs-flipkart-image-fix',
    name: 'Flipkart Product Image Compliance',
    category: 'E-commerce Fix',
    description: 'Fix product pictures to meet Flipkart strict listing standards: clean background, clear lighting, and exact aspect ratio.',
    price: 79,
    deliveryTime: 'Same Day',
    iconName: 'CheckCircle2',
    imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=800&q=80',
    popular: true,
    enabled: true,
    commonProblems: [
      'Meet Flipkart listing compliance standards',
      'Optimize image sharpness and true-to-life colors',
      'Provide 1100x1100px or higher for zoom enablement',
    ],
    supportedFileTypes: ['JPG', 'PNG'],
  },
];

export const quickFixOrdersInitialData: QuickFixOrder[] = [
  {
    id: 'QFIX-9482',
    serviceId: 'qs-bg-removal',
    serviceName: 'Background Removal',
    serviceCategory: 'Image Fix',
    customerName: 'Rahul Verma',
    customerEmail: 'rahul.verma@example.com',
    customerPhone: '+91 98765 43210',
    uploadedFileName: 'sneaker_sample_photo.jpg',
    uploadedFileUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    uploadedFileSize: '1.8 MB',
    uploadedFileType: 'image/jpeg',
    selectedRequirement: 'Isolate product with sharp clean edges',
    additionalInstructions: 'Need transparent PNG with sharp edges around laces and red mesh.',
    quantity: 1,
    unitPrice: 49,
    rushDelivery: false,
    totalPrice: 49,
    status: 'Delivered',
    estimatedDelivery: 'Same Day (1-2 hrs)',
    completedFileUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    completedFileName: 'sneaker_sample_transparent_fixed.png',
    completedFileSize: '920 KB',
    designerNotes: 'Clean alpha channel cutout with feather radius 0.5px. Output in 32-bit transparent PNG.',
    adminNotes: 'Order completed and delivered by Annu Dhaneja.',
    paymentStatus: 'Paid',
    paymentId: 'pay_rzp_mock_101',
    createdAt: new Date(Date.now() - 3600000 * 26).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'QFIX-9483',
    serviceId: 'qs-amazon-image-fix',
    serviceName: 'Amazon Main Image (Pure White RGB 255)',
    serviceCategory: 'E-commerce Fix',
    customerName: 'Pooja Agarwal',
    customerEmail: 'pooja.agarwal@example.com',
    customerPhone: '+91 98221 55678',
    uploadedFileName: 'perfume_bottle_raw.jpg',
    uploadedFileUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    uploadedFileSize: '2.4 MB',
    uploadedFileType: 'image/jpeg',
    selectedRequirement: 'Guarantee 100% Pure White RGB (255, 255, 255) background',
    additionalInstructions: 'Amazon rejected our listing due to greyish background corners. Please make it 100% pure white RGB 255.',
    quantity: 1,
    unitPrice: 79,
    rushDelivery: true,
    totalPrice: 128,
    status: 'In Progress',
    estimatedDelivery: '1-Hour Express Fix',
    adminNotes: 'Client selected rush delivery. Annu is working on white balance match and contact shadow.',
    paymentStatus: 'Paid',
    paymentId: 'pay_rzp_mock_102',
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'QFIX-9484',
    serviceId: 'qs-logo-cleanup',
    serviceName: 'Logo Cleanup & Vectorization',
    serviceCategory: 'Logo Fix',
    customerName: 'Anil Mehta',
    customerEmail: 'anil.m@crafts.in',
    uploadedFileName: 'old_logo_screenshot.png',
    uploadedFileUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=800&q=80',
    uploadedFileSize: '450 KB',
    uploadedFileType: 'image/png',
    selectedRequirement: 'Recreate low-res blurry logo in crisp vector format',
    additionalInstructions: 'Need high-res SVG and printable PDF for business cards.',
    quantity: 1,
    unitPrice: 149,
    rushDelivery: false,
    totalPrice: 149,
    status: 'Quality Check',
    estimatedDelivery: 'Same Day',
    completedFileUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=800&q=80',
    completedFileName: 'crafts_logo_vector_master.svg',
    completedFileSize: '180 KB',
    designerNotes: 'Vector nodes redrawn cleanly. Typography bezier curves balanced.',
    paymentStatus: 'Paid',
    paymentId: 'pay_rzp_mock_103',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
];
