import React from 'react';
import {
  Eraser,
  Image as ImageIcon,
  UserX,
  Crop,
  Maximize2,
  Columns,
  Minimize2,
  Sparkles,
  Eye,
  Layers,
  Palette,
  Sun,
  PenTool,
  Shield,
  Award,
  Type,
  Edit3,
  Search,
  Droplets,
  Share2,
  Instagram,
  Smartphone,
  Video,
  MessageCircle,
  Printer,
  FileText,
  File,
  Repeat,
  RefreshCw,
  FileCheck,
  Feather,
  UserCheck,
  AlignLeft,
  CheckSquare,
  ZoomIn,
  ShoppingBag,
  CheckCircle,
  CheckCircle2,
  Zap,
  Wrench,
  HelpCircle,
  Sliders,
  Scissors,
} from 'lucide-react';

interface QuickServiceIconProps {
  name: string;
  className?: string;
}

export const QuickServiceIcon: React.FC<QuickServiceIconProps> = ({ name, className = 'w-5 h-5' }) => {
  const iconMap: Record<string, React.ReactElement> = {
    Eraser: <Eraser className={className} />,
    Image: <ImageIcon className={className} />,
    UserX: <UserX className={className} />,
    Crop: <Crop className={className} />,
    Maximize2: <Maximize2 className={className} />,
    Columns: <Columns className={className} />,
    Minimize2: <Minimize2 className={className} />,
    Sparkles: <Sparkles className={className} />,
    Eye: <Eye className={className} />,
    Layers: <Layers className={className} />,
    Palette: <Palette className={className} />,
    Sparkle: <Sparkles className={className} />,
    Sun: <Sun className={className} />,
    PenTool: <PenTool className={className} />,
    Shield: <Shield className={className} />,
    Award: <Award className={className} />,
    Type: <Type className={className} />,
    Edit3: <Edit3 className={className} />,
    Search: <Search className={className} />,
    Droplets: <Droplets className={className} />,
    Share2: <Share2 className={className} />,
    Instagram: <Instagram className={className} />,
    Smartphone: <Smartphone className={className} />,
    Video: <Video className={className} />,
    MessageCircle: <MessageCircle className={className} />,
    Printer: <Printer className={className} />,
    FileText: <FileText className={className} />,
    File: <File className={className} />,
    Repeat: <Repeat className={className} />,
    RefreshCw: <RefreshCw className={className} />,
    FileCheck: <FileCheck className={className} />,
    Feather: <Feather className={className} />,
    UserCheck: <UserCheck className={className} />,
    AlignLeft: <AlignLeft className={className} />,
    CheckSquare: <CheckSquare className={className} />,
    ZoomIn: <ZoomIn className={className} />,
    ShoppingBag: <ShoppingBag className={className} />,
    CheckCircle: <CheckCircle className={className} />,
    CheckCircle2: <CheckCircle2 className={className} />,
    Zap: <Zap className={className} />,
    Wrench: <Wrench className={className} />,
    Sliders: <Sliders className={className} />,
    Scissors: <Scissors className={className} />,
  };

  return iconMap[name] || <Wrench className={className} />;
};
